### ISSUE TITLE
Use UB-Mannheim/ocr-fileformat as a starting point?

### ISSUE THREAD

**Issue by stweil** [OCR-D/format-converters#2]
[UB-Mannheim/ocr-fileformat](https://github.com/UB-Mannheim/ocr-fileformat/) already contains some converters.

**Comment by cneud** [comment]
See also [cneud/ocr-conversion-scripts](https://github.com/cneud/ocr-conversion-scripts). My personal preference would be an XSLT processor with some included stylesheets.

**Comment by wrznr** [comment]
@stweil @kba We actually thought it was the other way around: Providing XSLT style sheets here is the right way to support/extend https://github.com/UB-Mannheim/ocr-fileformat/ 

Do you prefer the style sheets to "live" in https://github.com/UB-Mannheim/ocr-fileformat/ ?

**Comment by kba** [comment]
> Do you prefer the style sheets to "live" in UB-Mannheim/ocr-fileformat ?

No, it's preferable to have them in a dedicated repository like this one or @cneud's. ocr-fileformat fetches stylesheets, schemas and scripts at build time from various sources, mostly repositories.
